# docker-compose.dev.yml
# 說明：專為本地開發設計，支援程式碼熱重載 (Hot-Reloading)。
# 執行：docker-compose -f docker-compose.dev.yml up --build -d
version: '3.8'

services:
  # -------------------------------------------------
  #  1. 基礎設施層 (與生產環境一致)
  # -------------------------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: dev_postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - dev_pgdata:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "15432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dev_redis_cache
    ports:
      - "6379:6379"
    volumes:
      - dev_redisdata:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: dev_rabbitmq_queue
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  etcd:
    container_name: dev_milvus-etcd
    image: quay.io/coreos/etcd:v3.6.1
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - dev_etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: dev_milvus-minio
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - dev_minio:/data
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus:
    image: milvusdb/milvus:v2.5.14
    command: ["milvus", "run", "standalone"]
    container_name: dev_milvus_vector_db
    depends_on:
      - etcd
      - minio
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - dev_milvusdata:/milvus/data
    ports:
      - "19530:19530"
      - "9091:9091"

  # -------------------------------------------------
  #  2. 應用程式層 (開發模式)
  # -------------------------------------------------
  web-app:
    build:
      context: ./services/web-app
      dockerfile: Dockerfile
    container_name: dev_web_app_service
    ports:
      - "5000:5000"
    volumes:
      # 掛載本地程式碼到容器中，實現熱重載
      - ./services/web-app/app:/usr/src/app
    environment:
      - FLASK_ENV=development # 啟用 Flask 開發模式
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure

  ai-worker:
    build:
      context: ./services/ai-worker
      dockerfile: Dockerfile
    container_name: dev_ai_worker_service
    volumes:
      # 掛載本地程式碼，若有修改可重啟容器生效
      - ./services/ai-worker/worker:/app/worker
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - LLM_SERVICE_URL=http://llm-service:8000
      - STT_SERVICE_URL=http://stt-service:8000
      - TTS_SERVICE_URL=http://tts-service:8000
    depends_on:
      - rabbitmq
      - postgres
      - redis
      - llm-service
      - stt-service
      - tts-service
    restart: on-failure

  # -------------------------------------------------
  #  3. AI 微服務層 (開發模式)
  # -------------------------------------------------
  llm-service:
    build:
      context: ./services/llm-service
      dockerfile: Dockerfile
    container_name: dev_llm_service
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    ports:
      - "8001:8000"
    depends_on:
      - milvus
    restart: on-failure

  stt-service:
    build:
      context: ./services/stt-service
      dockerfile: Dockerfile
    container_name: dev_stt_service
    ports:
      - "8002:8000"
    restart: on-failure

  tts-service:
    build:
      context: ./services/tts-service
      dockerfile: Dockerfile
    container_name: dev_tts_service
    ports:
      - "8003:8000"
    restart: on-failure

# -------------------------------------------------
#  4. 具名磁碟區 (開發環境)
# -------------------------------------------------
volumes:
  dev_pgdata:
  dev_redisdata:
  dev_milvusdata:
  dev_minio:
  dev_etcd:
